import logging

logger = logging.getLogger(__name__)

# Stub configuration
TELEGRAM_BOT_TOKEN = "STUB_BOT_TOKEN"
TELEGRAM_CHAT_ID = "STUB_CHAT_ID"

def format_alert_message(raw_message: str) -> str:
    """Formats the raw message for Telegram."""
    return f"🚨 *Project Syn Alert* 🚨\n\n{raw_message}\n\n_Generated by Mainframe Core_"

def dispatch_alert(message: str):
    """
    Stub function to send an alert to a Telegram channel.
    In a real implementation, this would make an HTTP POST request to the Telegram Bot API.
    """
    formatted_message = format_alert_message(message)
    logger.info(f"Telegram alert dispatched (STUB): \n{formatted_message}")
    # Example actual implementation using requests or httpx:
    # url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    # payload = {"chat_id": TELEGRAM_CHAT_ID, "text": formatted_message, "parse_mode": "Markdown"}
    # httpx.post(url, json=payload)
